name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        run: yarn install
      - name: EsLint
        run: yarn lint 
      - name: Jest
        run: yarn test
